# Generated by Django 3.2.13 on 2022-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image1',
            field=models.ImageField(null=True, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='job',
            name='image2',
            field=models.ImageField(null=True, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='job',
            name='image3',
            field=models.ImageField(null=True, upload_to='picture'),
        ),
    ]
