# Generated by Django 3.2.13 on 2022-04-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_alter_job_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
