# Generated by Django 3.2.13 on 2022-04-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
