# Generated by Django 3.2.13 on 2022-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.IntegerField(max_length=100),
        ),
    ]
