# Generated by Django 3.2.13 on 2022-04-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_alter_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
