# Generated by Django 3.2.13 on 2022-04-24 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField()),
                ('image1', models.ImageField(null=True, upload_to='picture')),
                ('image2', models.ImageField(null=True, upload_to='picture')),
                ('image3', models.ImageField(null=True, upload_to='picture')),
                ('vacancy', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
