# Generated by Django 3.2.13 on 2022-04-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
