# Generated by Django 3.2.13 on 2022-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(null=True, upload_to='pictures', verbose_name='resume'),
        ),
    ]
